// file generated by ChatGPT

// --- IMPORT FIREBASE MODULES ---
import * as FirebaseApp from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import * as FirebaseAuth from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import * as FirebaseStore from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

export class FirebaseController {
    FirebaseController() {
    }
    async init() {
        const firebaseConfig = {
            apiKey: "AIzaSyCehCZKaxW-_qYW5-Vvk9JHJ8nBoLSNIm0",
            authDomain: "play-stefanteaches.firebaseapp.com",
            projectId: "play-stefanteaches",
            storageBucket: "play-stefanteaches.firebasestorage.app",
            messagingSenderId: "930663810506",
            appId: "1:930663810506:web:9312fb860a3477a5acfb33",
            measurementId: "G-X632E2E31S"
        };

        // Initialize Firebase
        const app = FirebaseApp.initializeApp(firebaseConfig);
        //const analytics = FirebaseAnalytics.getAnalytics(app);
        const auth = FirebaseAuth.getAuth(app);
        const db   = FirebaseStore.getFirestore(app);

        // --- GOOGLE LOGIN ---
        const loginBtn = document.getElementById("loginBtn");
        const userInfo = document.getElementById("userInfo");
        const logoutBtn = document.getElementById("logoutBtn");
        const saveScoreBtn = document.getElementById("saveScoreBtn");

        await FirebaseAuth.setPersistence(auth, FirebaseAuth.browserLocalPersistence);


        loginBtn.onclick = async () => {
            const provider = new FirebaseAuth.GoogleAuthProvider();
            try {
                const result = await FirebaseAuth.signInWithPopup(auth, provider);
                const user = result.user;

                userInfo.innerText = "Здравей, " + user.email;
                saveScoreBtn.disabled = false;
            } catch (err) {
            console.error(err);
            }
        };

        logoutBtn.onclick = async () => {
            try {
                await FirebaseAuth.signOut(auth);
                // UI updates happen automatically in onAuthStateChanged
            } catch (err) {
                console.error(err);
            }
    };

        // --- SAVE SCORE TO FIRESTORE ---
        saveScoreBtn.onclick = async () => {
            const user = auth.currentUser;
            if (!user) return alert("Login first!");

            const score = Math.floor(Math.random() * 100); // test score

            const ref = FirebaseStore.doc(db, "scores", user.uid);

            await FirebaseStore.setDoc(ref, {
                email: user.email,
                lastScore: score,
                timestamp: Date.now()
            });

            document.getElementById("result").innerText =
            "Saved score: " + score;
        };

        FirebaseAuth.onAuthStateChanged(auth, (user) => {
            if (user) {
                // User is signed in
                userInfo.innerText = "Signed in as: " + user.email;
                saveScoreBtn.disabled = false;
                loginBtn.style.display = "none";
                logoutBtn.style.display = "inline";
            } else {
                // User is signed out
                userInfo.innerText = "Not signed in";
                saveScoreBtn.disabled = true;

                loginBtn.style.display = "inline";
                logoutBtn.style.display = "none";
            }
        });
    }
}
