// file generated by ChatGPT

// --- IMPORT FIREBASE MODULES ---
import * as FirebaseApp from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import * as FirebaseAuth from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import * as FirebaseStore from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

export class FirebaseController {
    FirebaseController(uiController) {
        this.uiController = uiController;
    }
    static #firebaseConfig = {
        apiKey: "AIzaSyCehCZKaxW-_qYW5-Vvk9JHJ8nBoLSNIm0",
        authDomain: "play-stefanteaches.firebaseapp.com",
        projectId: "play-stefanteaches",
        storageBucket: "play-stefanteaches.firebasestorage.app",
        messagingSenderId: "930663810506",
        appId: "1:930663810506:web:9312fb860a3477a5acfb33",
        measurementId: "G-X632E2E31S"
    };
    async init() {

        // Initialize Firebase
        const app = FirebaseApp.initializeApp(FirebaseController.#firebaseConfig);
        //const analytics = FirebaseAnalytics.getAnalytics(app);
        this.auth = FirebaseAuth.getAuth(app);
        this.db   = FirebaseStore.getFirestore(app);

        // --- GOOGLE LOGIN ---

        await FirebaseAuth.setPersistence(this.auth, FirebaseAuth.browserLocalPersistence);

        loginBtn.onclick = this.login.bind(this);

        logoutBtn.onclick = this.logout.bind(this);

        saveScoreBtn.onclick = this.saveScore.bind(this, Math.floor(Math.random() * 100));

        FirebaseAuth.onAuthStateChanged(this.auth, (user) => {
            if (user) {
                // User is signed in
                userInfo.innerText = "Signed in as: " + user.email;
                saveScoreBtn.disabled = false;
                loginBtn.style.display = "none";
                logoutBtn.style.display = "inline";
            } else {
                // User is signed out
                userInfo.innerText = "Not signed in";
                saveScoreBtn.disabled = true;

                loginBtn.style.display = "inline";
                logoutBtn.style.display = "none";
            }
        });
    }

    async login() {
        const provider = new FirebaseAuth.GoogleAuthProvider();
        const result = await FirebaseAuth.signInWithPopup(this.auth, provider);
        const user = result.user;

        userInfo.innerText = "Здравей, " + user.email;
        saveScoreBtn.disabled = false;
    }

    async logout() {
        await FirebaseAuth.signOut(this.auth);
        // UI updates happen automatically in onAuthStateChanged
    }

    async saveScore(score) {
        const user = this.auth.currentUser;
        if (!user) return alert("Login first!");

        const ref = FirebaseStore.doc(this.db, "scores", user.uid);

        await FirebaseStore.setDoc(ref, {
            email: user.email,
            lastScore: score,
            timestamp: Date.now()
        });

        document.getElementById("result").innerText =
        "Saved score: " + score;
    }
}
