// file generated by ChatGPT

// --- IMPORT FIREBASE MODULES ---
import * as FirebaseApp from "firebase/app";
import * as FirebaseAuth from "firebase/auth";
import * as FirebaseStore from "firebase/firestore";
import type { UIController } from "./UI";

export class FirebaseController {
    private uiController?: UIController;
    private auth!: FirebaseAuth.Auth;
    private db!: FirebaseStore.Firestore;
    private loginBtn!: HTMLButtonElement;
    private logoutBtn!: HTMLButtonElement;
    private saveScoreBtn!: HTMLButtonElement;
    private userInfo!: HTMLElement;
    private resultEl!: HTMLElement;

    constructor(uiController?: UIController) {
        this.uiController = uiController;
    }
    static #firebaseConfig = {
        apiKey: "AIzaSyCehCZKaxW-_qYW5-Vvk9JHJ8nBoLSNIm0",
        authDomain: "play-stefanteaches.firebaseapp.com",
        projectId: "play-stefanteaches",
        storageBucket: "play-stefanteaches.firebasestorage.app",
        messagingSenderId: "930663810506",
        appId: "1:930663810506:web:9312fb860a3477a5acfb33",
        measurementId: "G-X632E2E31S"
    };
    async init(): Promise<void> {

        // Initialize Firebase
        const app = FirebaseApp.initializeApp(FirebaseController.#firebaseConfig);
        //const analytics = FirebaseAnalytics.getAnalytics(app);
        this.auth = FirebaseAuth.getAuth(app);
        this.db   = FirebaseStore.getFirestore(app);

        // --- GOOGLE LOGIN ---

        await FirebaseAuth.setPersistence(this.auth, FirebaseAuth.browserLocalPersistence);

        this.loginBtn = document.getElementById("loginBtn") as HTMLButtonElement;
        this.logoutBtn = document.getElementById("logoutBtn") as HTMLButtonElement;
        this.saveScoreBtn = document.getElementById("saveScoreBtn") as HTMLButtonElement;
        this.userInfo = document.getElementById("userInfo") as HTMLElement;
        this.resultEl = document.getElementById("result") as HTMLElement;

        this.loginBtn.onclick = this.login.bind(this);

        this.logoutBtn.onclick = this.logout.bind(this);

        this.saveScoreBtn.onclick = this.saveScore.bind(this, Math.floor(Math.random() * 100));

        FirebaseAuth.onAuthStateChanged(this.auth, (user) => {
            if (user) {
                // User is signed in
                this.userInfo.innerText = "Signed in as: " + user.email;
                this.saveScoreBtn.disabled = false;
                this.loginBtn.style.display = "none";
                this.logoutBtn.style.display = "inline";
            } else {
                // User is signed out
                this.userInfo.innerText = "Not signed in";
                this.saveScoreBtn.disabled = true;

                this.loginBtn.style.display = "inline";
                this.logoutBtn.style.display = "none";
            }
        });
    }

    async login(): Promise<void> {
        const provider = new FirebaseAuth.GoogleAuthProvider();
        const result = await FirebaseAuth.signInWithPopup(this.auth, provider);
        const user = result.user;

        this.userInfo.innerText = "Ð—Ð´Ñ€Ð°Ð²ÐµÐ¹, " + user.email;
        this.saveScoreBtn.disabled = false;
    }

    async logout(): Promise<void> {
        await FirebaseAuth.signOut(this.auth);
        // UI updates happen automatically in onAuthStateChanged
    }

    async saveScore(score: number): Promise<void> {
        const user = this.auth.currentUser;
        if (!user) return alert("Login first!");

        const ref = FirebaseStore.doc(this.db, "scores", user.uid);

        await FirebaseStore.setDoc(ref, {
            email: user.email,
            lastScore: score,
            timestamp: Date.now()
        });

        this.resultEl.innerText =
        "Saved score: " + score;
    }
}


